// frontend/components/Footer.vue
<template>

<footer class="footer nefo-footer">

<nav v-if="links && links.length" class="nefo-navi-links" >
			<ul v-for="category in links" class="nefo-links-bar" :key="category">
				<li class="nefo-link-title" v-html="category.title">

				</li>
			<span v-if="category.links && category.links.length">
			<li v-for="link in category.links" :key="link">
				<a v-bind:href="link.href" v-html="link.title"></a>
				</li>
			</span>
			</ul>
		</nav>

<span  v-if="disclaimers && disclaimers.length">
		<div v-for="disclaimer in disclaimers" class="nefo-copyright-container" :key="disclaimer.id">
			<div class="nefo-copyright" v-html="disclaimer">

			</div>
		</div>
		</span>

		<div v-if="icons && icons.length" class="nefo-footer-links">
			</div>
</footer>


</template>
<script>
export default {
props: {
links: Array,
disclaimers: Array,
icons: Array
},

async asyncData(){

}
}
</script>
<style scoped lang="sass">
.nefo-footer
 background-color: rgba(33, 33, 33, 0.5)
 color: white
 padding-top: 20px
 padding-bottom: 40px
 padding-left: 40px
 padding-top: 60px
 padding-right: 40px
 margin-top: -20px
 position: relative

.nefo-navi-links
 flex-wrap: wrap
 display: flex
 margin-bottom: 20px
 justify-content: space-between

.nefo-footer-links
 display: flex
 margin-top: 0px
 height: 50px
 width: 150px
 justify-content: space-between
 align-items: center
 margin-top: 40px

.nefo-icons
 width: 40px
 height: 40px
 color: white

.nefo-discord-icon
 width: 50px
 height: 50px

.nefo-link-title 
 font-size: 20px
 font-weight: bold
 color: white

.nefo-footer a:link, a:visited
 color: white !important

.nefo-navi-links ul
 list-style: none


.nefo-copyright 
 width: calc(100% - 90px)
 margin-left: 40px
 text-align: center
 margin-bottom: 50px

.nefo-copyright-container
 margin-bottom: -50px
</style>

// market-garden/components/Footer.tsx
import { FunctionComponent } from "react";
import styles from "./Footer.module.sass";

export const Footer: FunctionComponent<{
  links?: Array<{
    id: string;
    title: string;
    links: Array<{ href: string; title: string }>;
  }>;
  disclaimers?: Array<{ id: string; content: string }>;
}> = function Footer(props) {
  return (
    <footer className={`${styles["nefo-footer"]} footer nefo-footer`}>
      <nav className={`${styles["nefo-navi-links"]} nefo-navi-links`}>
        {props.links?.map((category) => {
          return (
            <ul
              className={`$[styles["nefo-links-bar"]} nefo-links-bar`}
              key={category.id}
            >
              <li className={`${styles["nefo-link-title"]} nefo-link-title`}>
                {" "}
                {category.title}{" "}
              </li>

              {category.links?.map((link) => {
                return (
                  <li key={link.href}>
                    <a href={link.href}> {link.title}</a>
                  </li>
                );
              })}
            </ul>
          );
        })}
      </nav>
      <div>
        {props.disclaimers?.map((disclaimer) => {
          return (
            <div
              className={`${styles["nefo-copyright"]} nefo-copyright`}
              key={disclaimer.id}
            >
              {" "}
              {disclaimer.content}{" "}
            </div>
          );
        })}
      </div>
    </footer>
  );
};
