// market-garden/components/navigationbar.tsx
import { FunctionComponent } from "react";
import styles from "./NavigationBar.module.sass";

export const NavigationBar: FunctionComponent = () => {
  return (
    <div className={`${styles["navigation-bar-container"]} navigation-bar-container`}>
      <div className={`${styles["navigation-bar"]} navigation-bar`}>
        <div className={`${styles["top-category-container"]} top-category-container`}>
          <div className={`${styles["nav-category"]} ${styles["home-category"]} nav-category home-category`}>
            <div className={`${styles["home-button"]} ${styles["button"]} home-button button`}></div>
          </div>
        </div>
        <div className="nav-category bottom-category">
          <div className="button profile-button"></div>
        </div>
      </div>
    </div>
  );
};

// frontend/components/NavigationBar.vue
<template>
<div class="navigation-bar-container">
<div class="navigation-bar">
<div class="nav-category home-category">
    <div class="home-button button">
    </div>
</div>
</div>
</div>
</template>
<script lang="ts">
import Component from 'vue-class-component';
import Vue from 'vue';

@Component
export default class NavigationBar extends Vue {
}

</script>
<style scoped lang="sass">
.navigation-bar-container
 position: fixed
 left: 0
 top: 0

.navigation-bar, .nav-category
 display: flex
 flex-direction: column
 height: auto

.navigation-bar
 position: relative
 width: 75px
 padding-top: 25px
 background-color: rgba(0, 0, 0, 90%) 
 height: 100vh

.navigation-bar .button 
 width: 50px 
 height: 50px
 border-radius: 15px

.home-button 
 background-image: url('/icon.png')
.nav-category
 align-items: center
</style>
